//
//  WeatherIcons.swift
//  SimpleWeather
//
//  Created by Dave Antoine on 10/5/23.
//

import Foundation

public struct WeatherIcons
{
    private init() {}
    
    // DAY
    static let DAY_SUNNY = "\u{f00d}"
    static let DAY_CLOUDY = "\u{f002}"
    static let DAY_CLOUDY_GUSTS = "\u{f000}"
    static let DAY_CLOUDY_WINDY = "\u{f001}"
    static let DAY_FOG = "\u{f003}"
    static let DAY_HAIL = "\u{f004}"
    static let DAY_HAZE = "\u{f0b6}"
    static let DAY_LIGHTNING = "\u{f005}"
    static let DAY_RAIN = "\u{f008}"
    static let DAY_RAIN_MIX = "\u{f006}"
    static let DAY_RAIN_WIND = "\u{f007}"
    static let DAY_SHOWERS = "\u{f009}"
    static let DAY_SLEET = "\u{f0b2}"
    static let DAY_SLEET_STORM = "\u{f068}"
    static let DAY_SNOW = "\u{f00a}"
    static let DAY_SNOW_THUNDERSTORM = "\u{f06b}"
    static let DAY_SNOW_WIND = "\u{f065}"
    static let DAY_SPRINKLE = "\u{f00b}"
    static let DAY_STORM_SHOWERS = "\u{f00e}"
    static let DAY_SUNNY_OVERCAST = "\u{f00c}"
    static let DAY_THUNDERSTORM = "\u{f010}"
    static let DAY_WINDY = "\u{f085}"
    static let DAY_HOT = "\u{f072}"
    static let DAY_CLOUDY_HIGH = "\u{f07d}"
    static let DAY_LIGHT_WIND = "\u{f0c4}"
    static let DAY_PARTLY_CLOUDY = "\u{f00c}-pc"

    // NIGHT_ALT
    static let NIGHT_CLEAR = "\u{f02e}"
    static let NIGHT_ALT_CLOUDY = "\u{f086}"
    static let NIGHT_ALT_CLOUDY_GUSTS = "\u{f022}"
    static let NIGHT_ALT_CLOUDY_WINDY = "\u{f023}"
    static let NIGHT_FOG = "\u{f04a}"
    static let NIGHT_ALT_HAIL = "\u{f024}"
    static let NIGHT_HAZE = "\u{f0b6}-nt"
    static let NIGHT_ALT_LIGHTNING = "\u{f025}"
    static let NIGHT_ALT_RAIN = "\u{f028}"
    static let NIGHT_ALT_RAIN_MIX = "\u{f026}"
    static let NIGHT_ALT_RAIN_WIND = "\u{f027}"
    static let NIGHT_ALT_SHOWERS = "\u{f029}"
    static let NIGHT_ALT_SLEET = "\u{f0b4}"
    static let NIGHT_ALT_SLEET_STORM = "\u{f06a}"
    static let NIGHT_ALT_SNOW = "\u{f02a}"
    static let NIGHT_ALT_SNOW_THUNDERSTORM = "\u{f06d}"
    static let NIGHT_ALT_SNOW_WIND = "\u{f067}"
    static let NIGHT_ALT_SPRINKLE = "\u{f02b}"
    static let NIGHT_ALT_STORM_SHOWERS = "\u{f02c}"
    static let NIGHT_OVERCAST = "\u{f00c}-nt"
    static let NIGHT_ALT_THUNDERSTORM = "\u{f02d}"
    static let NIGHT_WINDY = "\u{f085}-nt"
    static let NIGHT_HOT = "\u{f072}-nt"
    static let NIGHT_ALT_CLOUDY_HIGH = "\u{f07e}"
    static let NIGHT_LIGHT_WIND = "\u{f0c4}-nt"
    static let NIGHT_ALT_PARTLY_CLOUDY = "\u{f081}"

    // NEUTRAL
    static let CLOUD = "\u{f041}"
    static let CLOUDY = "\u{f013}"
    static let CLOUDY_GUSTS = "\u{f011}"
    static let CLOUDY_WINDY = "\u{f012}"
    static let FOG = "\u{f014}"
    static let HAIL = "\u{f015}"
    static let HAZE = "\u{f0b6}-neutral"
    static let LIGHTNING = "\u{f016}"
    static let RAIN = "\u{f019}"
    static let RAIN_MIX = "\u{f017}"
    static let RAIN_WIND = "\u{f018}"
    static let SHOWERS = "\u{f01a}"
    static let SLEET = "\u{f0b5}"
    static let SLEET_STORM = "\u{f0b5}-storm"
    static let SNOW = "\u{f01b}"
    static let SNOW_THUNDERSTORM = "\u{f01b}-tstorms"
    static let SNOW_WIND = "\u{f064}"
    static let SPRINKLE = "\u{f01c}"
    static let STORM_SHOWERS = "\u{f01d}"
    static let OVERCAST = "\u{f00c}-neutral"
    static let THUNDERSTORM = "\u{f01e}"
    static let WINDY = "\u{f021}"
    static let HOT = "\u{f072}-neutral"
    static let LIGHT_WIND = "\u{f0c4}-neutral"
    static let SMOG = "\u{f074}"
    static let SMOKE = "\u{f062}"
    static let DUST = "\u{f063}"
    static let SNOWFLAKE_COLD = "\u{f076}"
    static let STRONG_WIND = "\u{f050}"
    static let SANDSTORM = "\u{f082}"
    static let HURRICANE = "\u{f073}"
    static let TORNADO = "\u{f056}"

    static let FIRE = "\u{f0c7}"
    static let FLOOD = "\u{f07c}"
    static let VOLCANO = "\u{f0c8}"

    static let BAROMETER = "\u{f079}"
    static let HUMIDITY = "\u{f07a}"
    static let MOONRISE = "\u{f0c9}"
    static let MOONSET = "\u{f0ca}"
    static let RAINDROP = "\u{f078}"
    static let RAINDROPS = "\u{f04e}"
    static let SUNRISE = "\u{f051}"
    static let SUNSET = "\u{f052}"
    static let THERMOMETER = "\u{f055}"
    static let UMBRELLA = "\u{f084}"
    static let WIND_DIRECTION = "\u{f0b1}"
    static let DIRECTION_UP = "\u{f058}"
    static let DIRECTION_DOWN = "\u{f044}"

    // Beaufort
    static let WIND_BEAUFORT_0 = "\u{f0b7}"
    static let WIND_BEAUFORT_1 = "\u{f0b8}"
    static let WIND_BEAUFORT_2 = "\u{f0b9}"
    static let WIND_BEAUFORT_3 = "\u{f0ba}"
    static let WIND_BEAUFORT_4 = "\u{f0bb}"
    static let WIND_BEAUFORT_5 = "\u{f0bc}"
    static let WIND_BEAUFORT_6 = "\u{f0bd}"
    static let WIND_BEAUFORT_7 = "\u{f0be}"
    static let WIND_BEAUFORT_8 = "\u{f0bf}"
    static let WIND_BEAUFORT_9 = "\u{f0c0}"
    static let WIND_BEAUFORT_10 = "\u{f0c1}"
    static let WIND_BEAUFORT_11 = "\u{f0c2}"
    static let WIND_BEAUFORT_12 = "\u{f0c3}"

    // Moon Phase
    static let MOON_NEW = "\u{f095}"
    static let MOON_WAXING_CRESCENT_3 = "\u{f098}"
    static let MOON_FIRST_QUARTER = "\u{f09c}"
    static let MOON_WAXING_GIBBOUS_3 = "\u{f09f}"
    static let MOON_FULL = "\u{f0a3}"
    static let MOON_WANING_GIBBOUS_3 = "\u{f0a6}"
    static let MOON_THIRD_QUARTER = "\u{f0aa}"
    static let MOON_WANING_CRESCENT_3 = "\u{f0ad}"

    static let MOON_ALT_NEW = "\u{f0eb}"
    static let MOON_ALT_WAXING_CRESCENT_3 = "\u{f0d2}"
    static let MOON_ALT_FIRST_QUARTER = "\u{f0d6}"
    static let MOON_ALT_WAXING_GIBBOUS_3 = "\u{f0d9}"
    static let MOON_ALT_FULL = "\u{f0dd}"
    static let MOON_ALT_WANING_GIBBOUS_3 = "\u{f0e0}"
    static let MOON_ALT_THIRD_QUARTER = "\u{f0e4}"
    static let MOON_ALT_WANING_CRESCENT_3 = "\u{f0e7}"

    static let UV_INDEX = "\u{f00d}-uv"
    static let UV_INDEX_1 = "\u{f00d}-uv1"
    static let UV_INDEX_2 = "\u{f00d}-uv2"
    static let UV_INDEX_3 = "\u{f00d}-uv3"
    static let UV_INDEX_4 = "\u{f00d}-uv4"
    static let UV_INDEX_5 = "\u{f00d}-uv5"
    static let UV_INDEX_6 = "\u{f00d}-uv6"
    static let UV_INDEX_7 = "\u{f00d}-uv7"
    static let UV_INDEX_8 = "\u{f00d}-uv8"
    static let UV_INDEX_9 = "\u{f00d}-uv9"
    static let UV_INDEX_10 = "\u{f00d}-uv10"
    static let UV_INDEX_11 = "\u{f00d}-uv11"

    static let TREE_POLLEN = "\u{2eee}"
    static let GRASS_POLLEN = "\u{2eef}"
    static let RAGWEED_POLLEN = "\u{2eed}"

    static let FAHRENHEIT = "\u{f045}"
    static let CELSIUS = "\u{f03c}"

    // N/A
    static let NA = "\u{f07b}"

    static let PLACEHOLDER = "\u{2022}"
    static let EM_DASH = "\u{2014}"
}
