// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWeather.Utils;

namespace SimpleWeather.Data.Migrations.LocationDB
{
    [DbContext(typeof(LocationDBContext))]
    [Migration("20200213090025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("SimpleWeather.Location.Favorites", b =>
                {
                    b.Property<string>("query")
                        .HasColumnType("TEXT");

                    b.Property<int>("position")
                        .HasColumnType("INTEGER");

                    b.HasKey("query");

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("SimpleWeather.Location.LocationData", b =>
                {
                    b.Property<string>("query")
                        .HasColumnType("TEXT");

                    b.Property<double>("latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("locationSource")
                        .HasColumnName("locsource")
                        .HasColumnType("TEXT");

                    b.Property<int>("locationType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("tz_long")
                        .HasColumnType("TEXT");

                    b.Property<string>("weatherSource")
                        .HasColumnName("source")
                        .HasColumnType("TEXT");

                    b.HasKey("query");

                    b.ToTable("locations");
                });
#pragma warning restore 612, 618
        }
    }
}
