//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AQIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AQIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.AQIndex", typeof(AQIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air quality is considered satisfactory, and air pollution poses little or no risk.
        /// </summary>
        public static string aqi_desc_0_50 {
            get {
                return ResourceManager.GetString("aqi_desc_0_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members of sensitive groups may experience health effects. The general public is not likely to be affected..
        /// </summary>
        public static string aqi_desc_101_150 {
            get {
                return ResourceManager.GetString("aqi_desc_101_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects.
        /// </summary>
        public static string aqi_desc_151_200 {
            get {
                return ResourceManager.GetString("aqi_desc_151_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health warnings of emergency conditions. The entire population is more likely to be affected..
        /// </summary>
        public static string aqi_desc_201_300 {
            get {
                return ResourceManager.GetString("aqi_desc_201_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health alert: everyone may experience more serious health effects.
        /// </summary>
        public static string aqi_desc_300 {
            get {
                return ResourceManager.GetString("aqi_desc_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air quality is acceptable.
        /// </summary>
        public static string aqi_desc_51_100 {
            get {
                return ResourceManager.GetString("aqi_desc_51_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string aqi_level_0_50 {
            get {
                return ResourceManager.GetString("aqi_level_0_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhealthy for Sensitive Groups.
        /// </summary>
        public static string aqi_level_101_150 {
            get {
                return ResourceManager.GetString("aqi_level_101_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhealthy.
        /// </summary>
        public static string aqi_level_151_200 {
            get {
                return ResourceManager.GetString("aqi_level_151_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Unhealthy.
        /// </summary>
        public static string aqi_level_201_300 {
            get {
                return ResourceManager.GetString("aqi_level_201_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous.
        /// </summary>
        public static string aqi_level_300 {
            get {
                return ResourceManager.GetString("aqi_level_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string aqi_level_51_100 {
            get {
                return ResourceManager.GetString("aqi_level_51_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO.
        /// </summary>
        public static string units_co {
            get {
                return ResourceManager.GetString("units_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO2.
        /// </summary>
        public static string units_no2 {
            get {
                return ResourceManager.GetString("units_no2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO&lt;sub&gt;&lt;small&gt;2&lt;/small&gt;&lt;/sub&gt;.
        /// </summary>
        public static string units_no2_formatted {
            get {
                return ResourceManager.GetString("units_no2_formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O3.
        /// </summary>
        public static string units_o3 {
            get {
                return ResourceManager.GetString("units_o3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&lt;sub&gt;&lt;small&gt;3&lt;/small&gt;&lt;/sub&gt;.
        /// </summary>
        public static string units_o3_formatted {
            get {
                return ResourceManager.GetString("units_o3_formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM10.
        /// </summary>
        public static string units_pm10 {
            get {
                return ResourceManager.GetString("units_pm10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM&lt;sub&gt;&lt;small&gt;10&lt;/small&gt;&lt;/sub&gt;.
        /// </summary>
        public static string units_pm10_formatted {
            get {
                return ResourceManager.GetString("units_pm10_formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM2.5.
        /// </summary>
        public static string units_pm25 {
            get {
                return ResourceManager.GetString("units_pm25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM&lt;sub&gt;&lt;small&gt;2.5&lt;/small&gt;&lt;/sub&gt;.
        /// </summary>
        public static string units_pm25_formatted {
            get {
                return ResourceManager.GetString("units_pm25_formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO2.
        /// </summary>
        public static string units_so2 {
            get {
                return ResourceManager.GetString("units_so2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO&lt;sub&gt;&lt;small&gt;2&lt;/small&gt;&lt;/sub&gt;.
        /// </summary>
        public static string units_so2_formatted {
            get {
                return ResourceManager.GetString("units_so2_formatted", resourceCulture);
            }
        }
    }
}
