//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Beaufort {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Beaufort() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.Beaufort", typeof(Beaufort).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calm.
        /// </summary>
        public static string beaufort_0 {
            get {
                return ResourceManager.GetString("beaufort_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Air.
        /// </summary>
        public static string beaufort_1 {
            get {
                return ResourceManager.GetString("beaufort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm.
        /// </summary>
        public static string beaufort_10 {
            get {
                return ResourceManager.GetString("beaufort_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violent Storm.
        /// </summary>
        public static string beaufort_11 {
            get {
                return ResourceManager.GetString("beaufort_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurricane.
        /// </summary>
        public static string beaufort_12 {
            get {
                return ResourceManager.GetString("beaufort_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Breeze.
        /// </summary>
        public static string beaufort_2 {
            get {
                return ResourceManager.GetString("beaufort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentle Breeze.
        /// </summary>
        public static string beaufort_3 {
            get {
                return ResourceManager.GetString("beaufort_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Breeze.
        /// </summary>
        public static string beaufort_4 {
            get {
                return ResourceManager.GetString("beaufort_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Breeze.
        /// </summary>
        public static string beaufort_5 {
            get {
                return ResourceManager.GetString("beaufort_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Breeze.
        /// </summary>
        public static string beaufort_6 {
            get {
                return ResourceManager.GetString("beaufort_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Gale.
        /// </summary>
        public static string beaufort_7 {
            get {
                return ResourceManager.GetString("beaufort_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gale.
        /// </summary>
        public static string beaufort_8 {
            get {
                return ResourceManager.GetString("beaufort_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Gale.
        /// </summary>
        public static string beaufort_9 {
            get {
                return ResourceManager.GetString("beaufort_9", resourceCulture);
            }
        }
    }
}
