//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string accuweather {
            get {
                return ResourceManager.GetString("accuweather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string apple {
            get {
                return ResourceManager.GetString("apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weatherapi.
        /// </summary>
        public static string default_weather_provider {
            get {
                return ResourceManager.GetString("default_weather_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;enabled&quot;:false,&quot;locSource&quot;:&quot;Bing&quot;,&quot;newWeatherSource&quot;:&quot;&quot;}.
        /// </summary>
        public static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string meteofrance {
            get {
                return ResourceManager.GetString("meteofrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string Metno {
            get {
                return ResourceManager.GetString("Metno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string NWS {
            get {
                return ResourceManager.GetString("NWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string OpenWeather {
            get {
                return ResourceManager.GetString("OpenWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;enabled&quot;:true,&quot;locSource&quot;:&quot;Bing&quot;,&quot;newWeatherSource&quot;:&quot;&quot;}.
        /// </summary>
        public static string openweather_onecall {
            get {
                return ResourceManager.GetString("openweather_onecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string tomorrowio {
            get {
                return ResourceManager.GetString("tomorrowio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string weatherapi {
            get {
                return ResourceManager.GetString("weatherapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string weatherbitio {
            get {
                return ResourceManager.GetString("weatherbitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;enabled&quot;: true,
        ///        &quot;locSource&quot;: &quot;Bing&quot;,
        ///        &quot;newWeatherSource&quot;: &quot;&quot;
        ///}.
        /// </summary>
        public static string wunlocked {
            get {
                return ResourceManager.GetString("wunlocked", resourceCulture);
            }
        }
    }
}
