//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MoonPhases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoonPhases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.MoonPhases", typeof(MoonPhases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Quarter.
        /// </summary>
        public static string moonphase_firstqtr {
            get {
                return ResourceManager.GetString("moonphase_firstqtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Moon.
        /// </summary>
        public static string moonphase_full {
            get {
                return ResourceManager.GetString("moonphase_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter.
        /// </summary>
        public static string moonphase_lastqtr {
            get {
                return ResourceManager.GetString("moonphase_lastqtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Moon.
        /// </summary>
        public static string moonphase_new {
            get {
                return ResourceManager.GetString("moonphase_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning Crescent.
        /// </summary>
        public static string moonphase_wancrescent {
            get {
                return ResourceManager.GetString("moonphase_wancrescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning Gibbous.
        /// </summary>
        public static string moonphase_wangibbous {
            get {
                return ResourceManager.GetString("moonphase_wangibbous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing Crescent.
        /// </summary>
        public static string moonphase_waxcrescent {
            get {
                return ResourceManager.GetString("moonphase_waxcrescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing Gibbous.
        /// </summary>
        public static string moonphase_waxgibbous {
            get {
                return ResourceManager.GetString("moonphase_waxgibbous", resourceCulture);
            }
        }
    }
}
