//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string action_editmode {
            get {
                return ResourceManager.GetString("action_editmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string action_refresh {
            get {
                return ResourceManager.GetString("action_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string action_reset {
            get {
                return ResourceManager.GetString("action_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string action_retry {
            get {
                return ResourceManager.GetString("action_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (Show all alerts).
        /// </summary>
        public static string alertsev_all {
            get {
                return ResourceManager.GetString("alertsev_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string alertsev_extreme {
            get {
                return ResourceManager.GetString("alertsev_extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string alertsev_moderate {
            get {
                return ResourceManager.GetString("alertsev_moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        public static string alertsev_severe {
            get {
                return ResourceManager.GetString("alertsev_severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Weather.
        /// </summary>
        public static string api_apple_weather {
            get {
                return ResourceManager.GetString("api_apple_weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weather Provider.
        /// </summary>
        public static string API_Box_PlaceholderText {
            get {
                return ResourceManager.GetString("API_Box.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Sky (DWD).
        /// </summary>
        public static string api_brightsky {
            get {
                return ResourceManager.GetString("api_brightsky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment and Climate Change Canada (ECCC).
        /// </summary>
        public static string api_eccc {
            get {
                return ResourceManager.GetString("api_eccc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string api_google {
            get {
                return ResourceManager.GetString("api_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERE Weather.
        /// </summary>
        public static string api_here {
            get {
                return ResourceManager.GetString("api_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Provider.
        /// </summary>
        public static string api_label {
            get {
                return ResourceManager.GetString("api_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationIQ.
        /// </summary>
        public static string api_lociq {
            get {
                return ResourceManager.GetString("api_lociq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MET Norway.
        /// </summary>
        public static string api_metno {
            get {
                return ResourceManager.GetString("api_metno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. National Weather Service.
        /// </summary>
        public static string api_nws {
            get {
                return ResourceManager.GetString("api_nws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWeatherMap.
        /// </summary>
        public static string api_owm {
            get {
                return ResourceManager.GetString("api_owm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.io.
        /// </summary>
        public static string api_tomorrowio {
            get {
                return ResourceManager.GetString("api_tomorrowio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Air Quality Index Project.
        /// </summary>
        public static string api_waqi {
            get {
                return ResourceManager.GetString("api_waqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherAPI.com.
        /// </summary>
        public static string api_weatherapi {
            get {
                return ResourceManager.GetString("api_weatherapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherUnlocked.
        /// </summary>
        public static string api_wunlocked {
            get {
                return ResourceManager.GetString("api_wunlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleWeather.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo by.
        /// </summary>
        public static string attrib_prefix {
            get {
                return ResourceManager.GetString("attrib_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckUpdatePrompt_Text {
            get {
                return ResourceManager.GetString("CheckUpdatePrompt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ConfirmDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("ConfirmDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Weather and (Apple) Weather are trademarks of Apple Inc..
        /// </summary>
        public static string copyright_apple_weather {
            get {
                return ResourceManager.GetString("copyright_apple_weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from.
        /// </summary>
        public static string credit_prefix {
            get {
                return ResourceManager.GetString("credit_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d ago.
        /// </summary>
        public static string DateTime_DayAgo {
            get {
                return ResourceManager.GetString("DateTime_DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h ago.
        /// </summary>
        public static string DateTime_HrAgo {
            get {
                return ResourceManager.GetString("DateTime_HrAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m ago.
        /// </summary>
        public static string DateTime_MinAgo {
            get {
                return ResourceManager.GetString("DateTime_MinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s ago.
        /// </summary>
        public static string DateTime_SecAgo {
            get {
                return ResourceManager.GetString("DateTime_SecAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string datetime_validuntil {
            get {
                return ResourceManager.GetString("datetime_validuntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F, mph, in, inHg, mi.
        /// </summary>
        public static string default_units_imperial {
            get {
                return ResourceManager.GetString("default_units_imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C, km/h, mm, mb, km.
        /// </summary>
        public static string default_units_metric {
            get {
                return ResourceManager.GetString("default_units_metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string DownloadingPrompt {
            get {
                return ResourceManager.GetString("DownloadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location access denied.
        /// </summary>
        public static string error_location_denied {
            get {
                return ResourceManager.GetString("error_location_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not supported by this weather provider.
        /// </summary>
        public static string error_message_weather_region_unsupported {
            get {
                return ResourceManager.GetString("error_message_weather_region_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string error_noresults {
            get {
                return ResourceManager.GetString("error_noresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location.
        /// </summary>
        public static string error_retrieve_location {
            get {
                return ResourceManager.GetString("error_retrieve_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Background Image.
        /// </summary>
        public static string FeatureOption_TileBackground_Content {
            get {
                return ResourceManager.GetString("FeatureOption_TileBackground.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features_Content {
            get {
                return ResourceManager.GetString("Features.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeebackButton_Content {
            get {
                return ResourceManager.GetString("FeebackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Code/Key.
        /// </summary>
        public static string hint_appcode {
            get {
                return ResourceManager.GetString("hint_appcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        public static string hint_appid {
            get {
                return ResourceManager.GetString("hint_appid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string hint_password {
            get {
                return ResourceManager.GetString("hint_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string hint_username {
            get {
                return ResourceManager.GetString("hint_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install. Click to try again.
        /// </summary>
        public static string InstallErrorPrompt {
            get {
                return ResourceManager.GetString("InstallErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string InstallingPrompt {
            get {
                return ResourceManager.GetString("InstallingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Key.
        /// </summary>
        public static string key_hint {
            get {
                return ResourceManager.GetString("key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        public static string label_afternoon {
            get {
                return ResourceManager.GetString("label_afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality Index.
        /// </summary>
        public static string label_airquality {
            get {
                return ResourceManager.GetString("label_airquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string label_back {
            get {
                return ResourceManager.GetString("label_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beaufort.
        /// </summary>
        public static string label_beaufort {
            get {
                return ResourceManager.GetString("label_beaufort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        public static string label_btn_add_location {
            get {
                return ResourceManager.GetString("label_btn_add_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        public static string label_chance {
            get {
                return ResourceManager.GetString("label_chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudiness.
        /// </summary>
        public static string label_cloudiness {
            get {
                return ResourceManager.GetString("label_cloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string label_condition {
            get {
                return ResourceManager.GetString("label_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string label_count_high {
            get {
                return ResourceManager.GetString("label_count_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string label_count_low {
            get {
                return ResourceManager.GetString("label_count_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string label_count_moderate {
            get {
                return ResourceManager.GetString("label_count_moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string label_count_veryhigh {
            get {
                return ResourceManager.GetString("label_count_veryhigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string label_currentlocation {
            get {
                return ResourceManager.GetString("label_currentlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string label_day {
            get {
                return ResourceManager.GetString("label_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string label_details {
            get {
                return ResourceManager.GetString("label_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew Point.
        /// </summary>
        public static string label_dewpoint {
            get {
                return ResourceManager.GetString("label_dewpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string label_distance {
            get {
                return ResourceManager.GetString("label_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Label_Done {
            get {
                return ResourceManager.GetString("Label_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string label_eve {
            get {
                return ResourceManager.GetString("label_eve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a location.
        /// </summary>
        public static string label_fab_add_location {
            get {
                return ResourceManager.GetString("label_fab_add_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Locations.
        /// </summary>
        public static string label_favoritelocations {
            get {
                return ResourceManager.GetString("label_favoritelocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels Like.
        /// </summary>
        public static string label_feelslike {
            get {
                return ResourceManager.GetString("label_feelslike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string label_forecast {
            get {
                return ResourceManager.GetString("label_forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string label_getstarted {
            get {
                return ResourceManager.GetString("label_getstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string label_gpsfollow {
            get {
                return ResourceManager.GetString("label_gpsfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass Pollen.
        /// </summary>
        public static string label_grass_pollen {
            get {
                return ResourceManager.GetString("label_grass_pollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string label_high {
            get {
                return ResourceManager.GetString("label_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        public static string label_hourlyforecast {
            get {
                return ResourceManager.GetString("label_hourlyforecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string label_humidity {
            get {
                return ResourceManager.GetString("label_humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string label_low {
            get {
                return ResourceManager.GetString("label_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon Phase.
        /// </summary>
        public static string label_moonphase {
            get {
                return ResourceManager.GetString("label_moonphase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonrise.
        /// </summary>
        public static string label_moonrise {
            get {
                return ResourceManager.GetString("label_moonrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonset.
        /// </summary>
        public static string label_moonset {
            get {
                return ResourceManager.GetString("label_moonset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string label_moreinfo {
            get {
                return ResourceManager.GetString("label_moreinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string label_morning {
            get {
                return ResourceManager.GetString("label_morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string label_nav_alerts {
            get {
                return ResourceManager.GetString("label_nav_alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string label_nav_locations {
            get {
                return ResourceManager.GetString("label_nav_locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string label_nav_weathernow {
            get {
                return ResourceManager.GetString("label_nav_weathernow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string label_next {
            get {
                return ResourceManager.GetString("label_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string label_night {
            get {
                return ResourceManager.GetString("label_night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO DATA.
        /// </summary>
        public static string label_nodata {
            get {
                return ResourceManager.GetString("label_nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        public static string Label_Pin_Text {
            get {
                return ResourceManager.GetString("Label_Pin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollen Count.
        /// </summary>
        public static string label_pollen_count {
            get {
                return ResourceManager.GetString("label_pollen_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string label_pollen_grass {
            get {
                return ResourceManager.GetString("label_pollen_grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragweed.
        /// </summary>
        public static string label_pollen_ragweed {
            get {
                return ResourceManager.GetString("label_pollen_ragweed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string label_pollen_tree {
            get {
                return ResourceManager.GetString("label_pollen_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string label_precipitation {
            get {
                return ResourceManager.GetString("label_precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string label_pressure {
            get {
                return ResourceManager.GetString("label_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string label_qpf_rain {
            get {
                return ResourceManager.GetString("label_qpf_rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string label_qpf_snow {
            get {
                return ResourceManager.GetString("label_qpf_snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string label_radar {
            get {
                return ResourceManager.GetString("label_radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragweed Pollen.
        /// </summary>
        public static string label_ragweed_pollen {
            get {
                return ResourceManager.GetString("label_ragweed_pollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string label_series {
            get {
                return ResourceManager.GetString("label_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string label_speed {
            get {
                return ResourceManager.GetString("label_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string label_style_dark {
            get {
                return ResourceManager.GetString("label_style_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string label_style_light {
            get {
                return ResourceManager.GetString("label_style_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        public static string label_sunrise {
            get {
                return ResourceManager.GetString("label_sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise / Sunset.
        /// </summary>
        public static string label_sunriseset {
            get {
                return ResourceManager.GetString("label_sunriseset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string label_sunset {
            get {
                return ResourceManager.GetString("label_sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string label_temp {
            get {
                return ResourceManager.GetString("label_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string label_temperature {
            get {
                return ResourceManager.GetString("label_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Pollen.
        /// </summary>
        public static string label_tree_pollen {
            get {
                return ResourceManager.GetString("label_tree_pollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin from Start.
        /// </summary>
        public static string Label_Unpin_Text {
            get {
                return ResourceManager.GetString("Label_Unpin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV Index.
        /// </summary>
        public static string label_uv {
            get {
                return ResourceManager.GetString("label_uv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string label_visibility {
            get {
                return ResourceManager.GetString("label_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string label_wind {
            get {
                return ResourceManager.GetString("label_wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Gust.
        /// </summary>
        public static string label_windgust {
            get {
                return ResourceManager.GetString("label_windgust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Location.
        /// </summary>
        public static string location_search_hint {
            get {
                return ResourceManager.GetString("location_search_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Provider Key.
        /// </summary>
        public static string message_enter_apikey {
            get {
                return ResourceManager.GetString("message_enter_apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location removed.
        /// </summary>
        public static string message_locationremoved {
            get {
                return ResourceManager.GetString("message_locationremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one favorite location.
        /// </summary>
        public static string message_needfavorite {
            get {
                return ResourceManager.GetString("message_needfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background access denied. Please enable in Settings..
        /// </summary>
        public static string Msg_BGAccessDeniedSettings {
            get {
                return ResourceManager.GetString("Msg_BGAccessDeniedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to location was denied. Please enable in Settings..
        /// </summary>
        public static string Msg_LocDeniedSettings {
            get {
                return ResourceManager.GetString("Msg_LocDeniedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Notification.
        /// </summary>
        public static string not_channel_name_dailynotification {
            get {
                return ResourceManager.GetString("not_channel_name_dailynotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation Notification.
        /// </summary>
        public static string not_channel_name_precipnotification {
            get {
                return ResourceManager.GetString("not_channel_name_precipnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        public static string NoUpdateAvailablePrompt {
            get {
                return ResourceManager.GetString("NoUpdateAvailablePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No weather alerts available..
        /// </summary>
        public static string NoWeatherAlerts_Prompt_Text {
            get {
                return ResourceManager.GetString("NoWeatherAlerts_Prompt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain will start in about {0}.
        /// </summary>
        public static string Precipitation_Minutely_Starting_Text_Format {
            get {
                return ResourceManager.GetString("Precipitation_Minutely_Starting_Text_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain will stop in about {0}.
        /// </summary>
        public static string Precipitation_Minutely_Stopping_Text_Format {
            get {
                return ResourceManager.GetString("Precipitation_Minutely_Stopping_Text_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% chance of rain in the next hour.
        /// </summary>
        public static string Precipitation_NextHour_Text_Format {
            get {
                return ResourceManager.GetString("Precipitation_NextHour_Text_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% chance of rain in {1}.
        /// </summary>
        public static string Precipitation_Text_Format {
            get {
                return ResourceManager.GetString("Precipitation_Text_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string pref_category_notification {
            get {
                return ResourceManager.GetString("pref_category_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Providers.
        /// </summary>
        public static string pref_category_providers {
            get {
                return ResourceManager.GetString("pref_category_providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string pref_category_support {
            get {
                return ResourceManager.GetString("pref_category_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string pref_category_version {
            get {
                return ResourceManager.GetString("pref_category_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features to enable/disable:.
        /// </summary>
        public static string Pref_Features_Subtitle_Text {
            get {
                return ResourceManager.GetString("Pref_Features_Subtitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Pref_Features_Title_Text {
            get {
                return ResourceManager.GetString("Pref_Features_Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Pref_GeneralHeader_Text {
            get {
                return ResourceManager.GetString("Pref_GeneralHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notifications for weather alerts.
        /// </summary>
        public static string pref_summary_alerts {
            get {
                return ResourceManager.GetString("pref_summary_alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather alerts are not supported by this weather provider.
        /// </summary>
        public static string pref_summary_alerts_disabled {
            get {
                return ResourceManager.GetString("pref_summary_alerts_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Provider Key required for %1$s.
        /// </summary>
        public static string pref_summary_apikey {
            get {
                return ResourceManager.GetString("pref_summary_apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account to register for a Provider key.
        /// </summary>
        public static string pref_summary_apiregister {
            get {
                return ResourceManager.GetString("pref_summary_apiregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display units in Celsius.
        /// </summary>
        public static string pref_summary_celsius {
            get {
                return ResourceManager.GetString("pref_summary_celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to current location via GPS.
        /// </summary>
        public static string pref_summary_currentlocation {
            get {
                return ResourceManager.GetString("pref_summary_currentlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display units in Fahrenheit.
        /// </summary>
        public static string pref_summary_fahrenheit {
            get {
                return ResourceManager.GetString("pref_summary_fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features to enable/disable.
        /// </summary>
        public static string pref_summary_features {
            get {
                return ResourceManager.GetString("pref_summary_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report any bugs or suggestions to improve the app.
        /// </summary>
        public static string pref_summary_feedback {
            get {
                return ResourceManager.GetString("pref_summary_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string pref_summary_off {
            get {
                return ResourceManager.GetString("pref_summary_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string pref_summary_on {
            get {
                return ResourceManager.GetString("pref_summary_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use personal weather provider key.
        /// </summary>
        public static string pref_summary_personalkey {
            get {
                return ResourceManager.GetString("pref_summary_personalkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like the app? Help support by providing a review.
        /// </summary>
        public static string pref_summary_rateandreview {
            get {
                return ResourceManager.GetString("pref_summary_rateandreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help translate the app.
        /// </summary>
        public static string pref_summary_translate {
            get {
                return ResourceManager.GetString("pref_summary_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display units in:.
        /// </summary>
        public static string Pref_SummaryUnits_Text {
            get {
                return ResourceManager.GetString("Pref_SummaryUnits.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string pref_title_about {
            get {
                return ResourceManager.GetString("pref_title_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SimpleWeather.
        /// </summary>
        public static string pref_title_about_app {
            get {
                return ResourceManager.GetString("pref_title_about_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Alerts.
        /// </summary>
        public static string pref_title_alerts {
            get {
                return ResourceManager.GetString("pref_title_alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Provider.
        /// </summary>
        public static string pref_title_api {
            get {
                return ResourceManager.GetString("pref_title_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string pref_title_apiregister {
            get {
                return ResourceManager.GetString("pref_title_apiregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string pref_title_credits {
            get {
                return ResourceManager.GetString("pref_title_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality Index.
        /// </summary>
        public static string pref_title_feature_aqindex {
            get {
                return ResourceManager.GetString("pref_title_feature_aqindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beaufort.
        /// </summary>
        public static string pref_title_feature_beaufort {
            get {
                return ResourceManager.GetString("pref_title_feature_beaufort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string pref_title_feature_bgimage {
            get {
                return ResourceManager.GetString("pref_title_feature_bgimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string pref_title_feature_charts {
            get {
                return ResourceManager.GetString("pref_title_feature_charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Details.
        /// </summary>
        public static string pref_title_feature_details {
            get {
                return ResourceManager.GetString("pref_title_feature_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string pref_title_feature_forecast {
            get {
                return ResourceManager.GetString("pref_title_feature_forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Forecast.
        /// </summary>
        public static string pref_title_feature_hrforecast {
            get {
                return ResourceManager.GetString("pref_title_feature_hrforecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Panel Image.
        /// </summary>
        public static string pref_title_feature_locpanelimg {
            get {
                return ResourceManager.GetString("pref_title_feature_locpanelimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon Phase.
        /// </summary>
        public static string pref_title_feature_moonphase {
            get {
                return ResourceManager.GetString("pref_title_feature_moonphase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Radar.
        /// </summary>
        public static string pref_title_feature_radar {
            get {
                return ResourceManager.GetString("pref_title_feature_radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Summary.
        /// </summary>
        public static string pref_title_feature_summary {
            get {
                return ResourceManager.GetString("pref_title_feature_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Phase.
        /// </summary>
        public static string pref_title_feature_sunphase {
            get {
                return ResourceManager.GetString("pref_title_feature_sunphase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV.
        /// </summary>
        public static string pref_title_feature_uv {
            get {
                return ResourceManager.GetString("pref_title_feature_uv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string pref_title_features {
            get {
                return ResourceManager.GetString("pref_title_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string pref_title_feedback {
            get {
                return ResourceManager.GetString("pref_title_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string pref_title_general {
            get {
                return ResourceManager.GetString("pref_title_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string pref_title_icons {
            get {
                return ResourceManager.GetString("pref_title_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string pref_title_language {
            get {
                return ResourceManager.GetString("pref_title_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Alert Severity.
        /// </summary>
        public static string pref_title_minalertseverity {
            get {
                return ResourceManager.GetString("pref_title_minalertseverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Notification.
        /// </summary>
        public static string pref_title_onnotification {
            get {
                return ResourceManager.GetString("pref_title_onnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Libraries.
        /// </summary>
        public static string pref_title_oslibs {
            get {
                return ResourceManager.GetString("pref_title_oslibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Provider Key.
        /// </summary>
        public static string pref_title_personalkey {
            get {
                return ResourceManager.GetString("pref_title_personalkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string pref_title_privacypolicy {
            get {
                return ResourceManager.GetString("pref_title_privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review.
        /// </summary>
        public static string pref_title_rateandreview {
            get {
                return ResourceManager.GetString("pref_title_rateandreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        public static string pref_title_refreshinterval {
            get {
                return ResourceManager.GetString("pref_title_refreshinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset units to default values.
        /// </summary>
        public static string pref_title_resetunits {
            get {
                return ResourceManager.GetString("pref_title_resetunits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string pref_title_termsofservice {
            get {
                return ResourceManager.GetString("pref_title_termsofservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string pref_title_time {
            get {
                return ResourceManager.GetString("pref_title_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string pref_title_translate {
            get {
                return ResourceManager.GetString("pref_title_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string pref_title_units {
            get {
                return ResourceManager.GetString("pref_title_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string pref_title_userthememode {
            get {
                return ResourceManager.GetString("pref_title_userthememode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not set. Please add a location.
        /// </summary>
        public static string prompt_location_not_set {
            get {
                return ResourceManager.GetString("prompt_location_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available. Click to install.
        /// </summary>
        public static string prompt_update_available {
            get {
                return ResourceManager.GetString("prompt_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SimpleWeather.
        /// </summary>
        public static string prompt_update_title {
            get {
                return ResourceManager.GetString("prompt_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        public static string refresh_12hrs {
            get {
                return ResourceManager.GetString("refresh_12hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string refresh_2hrs {
            get {
                return ResourceManager.GetString("refresh_2hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string refresh_30min {
            get {
                return ResourceManager.GetString("refresh_30min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 hours.
        /// </summary>
        public static string refresh_3hrs {
            get {
                return ResourceManager.GetString("refresh_3hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string refresh_60min {
            get {
                return ResourceManager.GetString("refresh_60min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 hours.
        /// </summary>
        public static string refresh_6hrs {
            get {
                return ResourceManager.GetString("refresh_6hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a location to start.
        /// </summary>
        public static string setup_location_prompt {
            get {
                return ResourceManager.GetString("setup_location_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your settings below.
        /// </summary>
        public static string setup_preferences_prompt {
            get {
                return ResourceManager.GetString("setup_preferences_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SimpleWeather.
        /// </summary>
        public static string setup_welcome_prompt {
            get {
                return ResourceManager.GetString("setup_welcome_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a simple weather app.
        /// </summary>
        public static string setup_welcome_tagline_prompt {
            get {
                return ResourceManager.GetString("setup_welcome_tagline_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string summary_default {
            get {
                return ResourceManager.GetString("summary_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string time_current {
            get {
                return ResourceManager.GetString("time_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string title_activity_settings {
            get {
                return ResourceManager.GetString("title_activity_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Settings.
        /// </summary>
        public static string title_dev_settings {
            get {
                return ResourceManager.GetString("title_dev_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Weather Alerts.
        /// </summary>
        public static string title_fragment_alerts {
            get {
                return ResourceManager.GetString("title_fragment_alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        public static string update_prefix {
            get {
                return ResourceManager.GetString("update_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at.
        /// </summary>
        public static string update_prefix_day {
            get {
                return ResourceManager.GetString("update_prefix_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string userthememode_dark {
            get {
                return ResourceManager.GetString("userthememode_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string userthememode_default {
            get {
                return ResourceManager.GetString("userthememode_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string userthememode_light {
            get {
                return ResourceManager.GetString("userthememode_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Provider Key.
        /// </summary>
        public static string werror_invalidkey {
            get {
                return ResourceManager.GetString("werror_invalidkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connection Error.
        /// </summary>
        public static string werror_networkerror {
            get {
                return ResourceManager.GetString("werror_networkerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load weather data.
        /// </summary>
        public static string werror_noweather {
            get {
                return ResourceManager.GetString("werror_noweather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cities match your search query.
        /// </summary>
        public static string werror_querynotfound {
            get {
                return ResourceManager.GetString("werror_querynotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred.
        /// </summary>
        public static string werror_unknown {
            get {
                return ResourceManager.GetString("werror_unknown", resourceCulture);
            }
        }
    }
}
