//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Units {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Units() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.Units", typeof(Units).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string unit_celsius {
            get {
                return ResourceManager.GetString("unit_celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string unit_cm {
            get {
                return ResourceManager.GetString("unit_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string unit_fahrenheit {
            get {
                return ResourceManager.GetString("unit_fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string unit_in {
            get {
                return ResourceManager.GetString("unit_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inHg.
        /// </summary>
        public static string unit_inHg {
            get {
                return ResourceManager.GetString("unit_inHg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string unit_kilometers {
            get {
                return ResourceManager.GetString("unit_kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knots.
        /// </summary>
        public static string unit_knots {
            get {
                return ResourceManager.GetString("unit_knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string unit_kph {
            get {
                return ResourceManager.GetString("unit_kph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mb.
        /// </summary>
        public static string unit_mBar {
            get {
                return ResourceManager.GetString("unit_mBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string unit_miles {
            get {
                return ResourceManager.GetString("unit_miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string unit_mm {
            get {
                return ResourceManager.GetString("unit_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmHg.
        /// </summary>
        public static string unit_mmHg {
            get {
                return ResourceManager.GetString("unit_mmHg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string unit_mph {
            get {
                return ResourceManager.GetString("unit_mph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string unit_msec {
            get {
                return ResourceManager.GetString("unit_msec", resourceCulture);
            }
        }
    }
}
