//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WeatherConditions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherConditions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.WeatherConditions", typeof(WeatherConditions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        public static string weather_blizzard {
            get {
                return ResourceManager.GetString("weather_blizzard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowing Snow.
        /// </summary>
        public static string weather_blowingsnow {
            get {
                return ResourceManager.GetString("weather_blowingsnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string weather_clear {
            get {
                return ResourceManager.GetString("weather_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sky.
        /// </summary>
        public static string weather_clearsky {
            get {
                return ResourceManager.GetString("weather_clearsky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string weather_cloudy {
            get {
                return ResourceManager.GetString("weather_cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold.
        /// </summary>
        public static string weather_cold {
            get {
                return ResourceManager.GetString("weather_cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        public static string weather_drizzle {
            get {
                return ResourceManager.GetString("weather_drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust.
        /// </summary>
        public static string weather_dust {
            get {
                return ResourceManager.GetString("weather_dust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        public static string weather_fair {
            get {
                return ResourceManager.GetString("weather_fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string weather_fog {
            get {
                return ResourceManager.GetString("weather_fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foggy.
        /// </summary>
        public static string weather_foggy {
            get {
                return ResourceManager.GetString("weather_foggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Rain.
        /// </summary>
        public static string weather_freezingrain {
            get {
                return ResourceManager.GetString("weather_freezingrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hail.
        /// </summary>
        public static string weather_hail {
            get {
                return ResourceManager.GetString("weather_hail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haze.
        /// </summary>
        public static string weather_haze {
            get {
                return ResourceManager.GetString("weather_haze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rain.
        /// </summary>
        public static string weather_heavyrain {
            get {
                return ResourceManager.GetString("weather_heavyrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Snow.
        /// </summary>
        public static string weather_heavysnow {
            get {
                return ResourceManager.GetString("weather_heavysnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string weather_hot {
            get {
                return ResourceManager.GetString("weather_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurricane.
        /// </summary>
        public static string weather_hurricane {
            get {
                return ResourceManager.GetString("weather_hurricane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolated Thunderstorms.
        /// </summary>
        public static string weather_isotstorms {
            get {
                return ResourceManager.GetString("weather_isotstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Fog.
        /// </summary>
        public static string weather_lightfog {
            get {
                return ResourceManager.GetString("weather_lightfog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Rain.
        /// </summary>
        public static string weather_lightrain {
            get {
                return ResourceManager.GetString("weather_lightrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Snow.
        /// </summary>
        public static string weather_lightsnowshowers {
            get {
                return ResourceManager.GetString("weather_lightsnowshowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Wind.
        /// </summary>
        public static string weather_lightwind {
            get {
                return ResourceManager.GetString("weather_lightwind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly Clear.
        /// </summary>
        public static string weather_mostlyclear {
            get {
                return ResourceManager.GetString("weather_mostlyclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly Cloudy.
        /// </summary>
        public static string weather_mostlycloudy {
            get {
                return ResourceManager.GetString("weather_mostlycloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string weather_notavailable {
            get {
                return ResourceManager.GetString("weather_notavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        public static string weather_overcast {
            get {
                return ResourceManager.GetString("weather_overcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly Cloudy.
        /// </summary>
        public static string weather_partlycloudy {
            get {
                return ResourceManager.GetString("weather_partlycloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string weather_rain {
            get {
                return ResourceManager.GetString("weather_rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Rain and Hail.
        /// </summary>
        public static string weather_rainandhail {
            get {
                return ResourceManager.GetString("weather_rainandhail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Rain and Sleet.
        /// </summary>
        public static string weather_rainandsleet {
            get {
                return ResourceManager.GetString("weather_rainandsleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Rain and Snow.
        /// </summary>
        public static string weather_rainandsnow {
            get {
                return ResourceManager.GetString("weather_rainandsnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain Showers.
        /// </summary>
        public static string weather_rainshowers {
            get {
                return ResourceManager.GetString("weather_rainshowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scattered Showers.
        /// </summary>
        public static string weather_scatteredshowers {
            get {
                return ResourceManager.GetString("weather_scatteredshowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scattered Thunderstorms.
        /// </summary>
        public static string weather_scatteredtstorms {
            get {
                return ResourceManager.GetString("weather_scatteredtstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Thunderstorms.
        /// </summary>
        public static string weather_severetstorms {
            get {
                return ResourceManager.GetString("weather_severetstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleet.
        /// </summary>
        public static string weather_sleet {
            get {
                return ResourceManager.GetString("weather_sleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleet and Thunder.
        /// </summary>
        public static string weather_sleet_tstorms {
            get {
                return ResourceManager.GetString("weather_sleet_tstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smog.
        /// </summary>
        public static string weather_smog {
            get {
                return ResourceManager.GetString("weather_smog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoky.
        /// </summary>
        public static string weather_smoky {
            get {
                return ResourceManager.GetString("weather_smoky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string weather_snow {
            get {
                return ResourceManager.GetString("weather_snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow and Thunder.
        /// </summary>
        public static string weather_snow_tstorms {
            get {
                return ResourceManager.GetString("weather_snow_tstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Snow and Sleet.
        /// </summary>
        public static string weather_snowandsleet {
            get {
                return ResourceManager.GetString("weather_snowandsleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow Flurries.
        /// </summary>
        public static string weather_snowflurries {
            get {
                return ResourceManager.GetString("weather_snowflurries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunny.
        /// </summary>
        public static string weather_sunny {
            get {
                return ResourceManager.GetString("weather_sunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado.
        /// </summary>
        public static string weather_tornado {
            get {
                return ResourceManager.GetString("weather_tornado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical Storm.
        /// </summary>
        public static string weather_tropicalstorm {
            get {
                return ResourceManager.GetString("weather_tropicalstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorms.
        /// </summary>
        public static string weather_tstorms {
            get {
                return ResourceManager.GetString("weather_tstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windy.
        /// </summary>
        public static string weather_windy {
            get {
                return ResourceManager.GetString("weather_windy", resourceCulture);
            }
        }
    }
}
