//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWeather.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindDirection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindDirection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWeather.Resources.Strings.WindDirection", typeof(WindDirection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string wind_dir_e {
            get {
                return ResourceManager.GetString("wind_dir_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENE.
        /// </summary>
        public static string wind_dir_ene {
            get {
                return ResourceManager.GetString("wind_dir_ene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESE.
        /// </summary>
        public static string wind_dir_ese {
            get {
                return ResourceManager.GetString("wind_dir_ese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string wind_dir_n {
            get {
                return ResourceManager.GetString("wind_dir_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string wind_dir_ne {
            get {
                return ResourceManager.GetString("wind_dir_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNE.
        /// </summary>
        public static string wind_dir_nne {
            get {
                return ResourceManager.GetString("wind_dir_nne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNW.
        /// </summary>
        public static string wind_dir_nnw {
            get {
                return ResourceManager.GetString("wind_dir_nnw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string wind_dir_nw {
            get {
                return ResourceManager.GetString("wind_dir_nw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string wind_dir_s {
            get {
                return ResourceManager.GetString("wind_dir_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string wind_dir_se {
            get {
                return ResourceManager.GetString("wind_dir_se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE.
        /// </summary>
        public static string wind_dir_sse {
            get {
                return ResourceManager.GetString("wind_dir_sse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSW.
        /// </summary>
        public static string wind_dir_ssw {
            get {
                return ResourceManager.GetString("wind_dir_ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string wind_dir_sw {
            get {
                return ResourceManager.GetString("wind_dir_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string wind_dir_w {
            get {
                return ResourceManager.GetString("wind_dir_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WNW.
        /// </summary>
        public static string wind_dir_wnw {
            get {
                return ResourceManager.GetString("wind_dir_wnw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSW.
        /// </summary>
        public static string wind_dir_wsw {
            get {
                return ResourceManager.GetString("wind_dir_wsw", resourceCulture);
            }
        }
    }
}
